{
 "title": "HCL Cache - Redis Cluster Dashboard",
 "tags": [
  "prometheus",
  "redis",
  "hcl"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_instance_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(redis_instance_info{namespace=\"$namespace\",role=\"master\"}, pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_instance_info{namespace=\"$namespace\",pod=\"$pod\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Master Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_instance_info{ namespace = \"$namespace\", role=\"master\"}"
    }
   ]
  },
  {
   "title": "Redis Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes * on (instance) group_left redis_instance_info{ namespace = \"$namespace\", role=\"master\"}",
     "legendFormat": "{{pod}} "
    },
    { "expr": "max(redis_memory_max_bytes)", "legendFormat": "max" }
   ]
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{namespace=\"$namespace\"}) by (pod) * on (pod) group_left redis_instance_info{ namespace = \"$namespace\", role=\"master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replica Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(label_replace(redis_instance_info{namespace=\"$namespace\", role=\"master\"}, \"master_host\", \"$1\", \"instance\", \"(.+):(\\\\d+)\"), \"master_pod\", \"$1\", \"pod\", \"(.+)\") * on (master_host) group_left (replica_pod, replica_host) label_replace( label_replace(redis_slave_info{namespace=\"$namespace\"}, \"replica_pod\", \"$1\", \"pod\", \"(.+)\"), \"replica_host\", \"$1\", \"instance\", \"(.+):(\\\\d+)\")\r\n"
    }
   ]
  },
  {
   "title": "Commands Calls/ sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{namespace=\"$namespace\"}[1m])) by (pod) * on (pod) group_left redis_instance_info{ namespace = \"$namespace\", role=\"master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{namespace=\"$namespace\"}[1m])) by (pod) * on (pod) group_left redis_instance_info{ namespace = \"$namespace\", role=\"master\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Known Nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_cluster_known_nodes{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_cluster_connections{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "SlowLog  Entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_slowlog_length{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=~\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "${pod}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(redis_uptime_in_seconds{instance=~\"$instance\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_connected_clients{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (redis_memory_used_bytes{instance=~\"$instance\"}  / redis_memory_max_bytes{instance=~\"$instance\"} )"
      }
     ]
    },
    {
     "title": "Commands Executed / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "hits"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "misses"
      }
     ]
    },
    {
     "title": "Redis connected clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_connected_clients{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "input"
      },
      {
       "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
       "legendFormat": "ouput"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "redis_memory_used_bytes{instance=~\"$instance\"} ",
       "legendFormat": "used"
      },
      {
       "expr": "redis_memory_max_bytes{instance=~\"$instance\"} ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
       "legendFormat": "not expiring"
      },
      {
       "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
       "legendFormat": "expiring"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{instance=~\"$instance\"}) ",
       "legendFormat": "{{ db }} "
      }
     ]
    },
    {
     "title": "HCL Caches",
     "type": "table",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "hclcache_cache_remote_node_mapping * on ( redis_host ) group_left () label_replace(redis_instance_info{namespace=\"$namespace\",pod=\"$pod\"},\"redis_host\", \"$1\", \"instance\", \"(.+):(\\\\d+)\")\r\n"
      }
     ]
    },
    {
     "title": "Command Calls / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"} [1m]))",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Expired / Evicted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "expired"
      },
      {
       "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
       "legendFormat": "evicted"
      }
     ]
    }
   ]
  }
 ]
}