{
 "title": "NiFi Performance",
 "tags": [ "hcl" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nifipod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests_cpu_cores{container=\"nifi-app\"},pod)"
    }
   },
   { "name": "es_datasource", "label": "connector", "query": "elasticsearch" },
   { "name": "prometheus_datasource", "label": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "connector",
    "label": "connector",
    "query": "{\"find\": \"terms\",  \"field\": \"connector\"}"
   },
   {
    "name": "runId",
    "label": "runId",
    "query": "{\"find\": \"terms\", \"field\": \"run\", \"query\": \"connector: $connector\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Explanation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Explanation",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "There are 3 types of metric data in this Nifi Dashboard.\n\n(1)Ingest Metrics is based on the Elasticsearch datasource to get ingest metrics based on connector type and runId. \n\n(2)Nifi metrics pulls out the metrics data based on the specified time range.\n\n(3)System Metrics pulls out the system metrics based on the specified time range."
     }
    }
   ]
  },
  {
   "title": "Setup Instructions for Elasticsearch Datasource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Setup for Elasticsearch datasource to access the ingest data",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "After the first ingest is done, an elasticsearch index \"run\" would be created.\nPlease do the following setup after your first ingest is done to view nifi statistics.\n\nAdd an elasticsearch datasource\n   1) Click on the configuration icon (with a wheel picture) on the side \n   2) Choose \"Data Sources\"\n   3) Click on \"Add data source\"\n   4) Type in \"Elasticsearch\" in the search field\n   5) Click on the returned \"Elasticsearch\" icon\n   6) Fill in the name of index (e.g. Elasticsearch)\n   7) Under section \"HTTP\", fill in the field \"URL\" with your elasticsearch domain and port              \n      something like http://elasticsearch-master.es.svc.cluster.local:9200/)      \n\t  The domain and port number could be changed based on the user deployment.\n   8) Under section \"Elastic details\", fill in the fields/choose the options as follows:                      \n\t\t(a) Index name : run   \n\t\t(b) Pattern : No pattern   \n\t\t(c) Time field name : date   \n\t\t(d) Version : 7.0+\n   9)Click on \"Save & Test\" button at the end of the page.          \n     Ensure the connection succeeds before the dashboard would work properly."
     }
    }
   ]
  },
  { "title": "Ingest Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Created Document Counters (only valid for reindex connector)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Write Success",
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND run: $runId  AND group: Create* AND name: \"Write Success\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "connector: $connector AND run: $runId AND group: Create* AND name: \"Write Failure\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Updated Document Counters ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Write Success",
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND run: $runId  AND NOT group: Create* AND name: \"Write Success\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "connector: $connector AND run: $runId AND NOT group: Create* AND name: \"Write Failure\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Absolute Elapsed Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "value.numeric", "id": "1", "type": "avg" }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative Elapsed Time\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Cumulative Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative Data Transformation Time\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative Bulk Time\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "value.numeric", "id": "1", "type": "sum" }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative Wait Time\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Cumulative SQL Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative SQL Execution Time\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative SQL Fetch Time\"",
     "timeField": "date"
    }
   ]
  },
  { "title": "Nifi General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Queued Items",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( nifi_amount_items_queued{ component_type = 'ProcessGroup' } ) by ( component_type, component_name )",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Wait Link",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( nifi_amount_items_queued{ component_type = 'ProcessGroup', component_name =~ '.*WaitLink.*' } ) by ( component_type, component_name )",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Container - $nifipod  System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "repeat": "nifipod"
  },
  {
   "title": "Heap Used (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(nifi_jvm_heap_usage{pod=\"$nifipod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Used (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nifi_jvm_heap_used{pod=\"$nifipod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=\"$nifipod\"}",
     "legendFormat": "nifi-app"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=\"$nifipod\"}\n",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=\"$nifipod\"}\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=\"$nifipod\", container=\"nifi-app\"}[5m])) /sum(increase(container_cpu_cfs_periods_total{pod=\"$nifipod\", container=\"nifi-app\"}[5m])) "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{ pod=\"$nifipod\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "working set"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=\"$nifipod\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$nifipod\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "sum(container_memory_cache{ pod=\"$nifipod\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "cache"
    },
    {
     "expr": "sum(container_memory_swap{ pod=\"$nifipod\", container!=\"POD\", container!=\"\"}) by (container)",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Disk I/O - reads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=\"$nifipod\", container =\"nifi-app\"}[5m])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O - writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=\"$nifipod\", container =\"nifi-app\"}[5m])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}