{
 "title": "Java - Detailed Metrics by Pod",
 "tags": [
  "hcl",
  "java"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=~\"$namespace\",job=~\"$job\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "jvm_memory_pool_heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{ namespace=~\"$namespace\", job=~\"$job\",pod=\"$pod\", area=\"heap\",},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "jvm_memory_pool_nonheap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{ namespace=~\"$namespace\", job=~\"$job\",pod=\"$pod\", area=\"nonheap\",},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_count{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "system_load_average_1m{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap Memory Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"heap\", id=\"$jvm_memory_pool_heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"heap\", id=\"$jvm_memory_pool_heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"heap\", id=\"$jvm_memory_pool_heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\", area=\"nonheap\", id=\"$jvm_memory_pool_nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "HCL Cache Netty used direct memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "hclcache_netty_used_direct_memory_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=\"$pod\"}",
       "legendFormat": "direct_memory"
      }
     ]
    }
   ]
  }
 ]
}