{
 "title": "QueryApp Servers",
 "tags": [ "hcl" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{container=\"query-app\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*query-app.*\"} , deployment) "
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\",workload=\"$job\" }, pod)"
    }
   },
   {
    "name": "resource",
    "label": "resource",
    "query": {
     "query": "label_values(request_rest_seconds_count{namespace=~\"$namespace\",job=\"$job\",pod=~\"$pod\"}, resource)"
    }
   },
   {
    "name": "http_status",
    "label": "http_status",
    "query": {
     "query": "label_values(request_rest_status_total{namespace=~\"$namespace\",job=\"$job\",pod=~\"$pod\",resource=~\"$resource\"}, http_status)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Image",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_info{ namespace=\"$namespace\", pod=~\"$pod\", container=\"query-app\" }\r\n* on(pod)\r\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" } \r"
      }
     ]
    },
    {
     "title": "Requests Status (per second)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\" }[2m]))  by (http_status) > 0",
       "legendFormat": "{{http_status}}"
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (job) / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "query-app pods",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{ namespace=\"$namespace\", deployment=~\"$job\"   }  ",
       "legendFormat": "available"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{ namespace=\"$namespace\", deployment=~\"$job\" }",
       "legendFormat": "unavailable"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources and Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "committed"
      },
      {
       "expr": "max(sum(jvm_memory_max_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "If the CPU Usage is not shown, please check the query in the panel \"CPU Usage\" in the dashboard \"General/Kubernetes/Compute Resources/Pod\" to see whether \"sum_rate\" is used instead of \"sum_irate\".  If it is the case, please update sum_irate in Query A in this panel to sum_rate.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$pod\", container=\"query-app\" }\n  * on(pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" }\n) by (pod)\n",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"query-app\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"query-app\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Default_Executor Thread pool",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(threadpool_maximum_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", pool=\"Default_Executor\" })",
       "legendFormat": "max"
      },
      {
       "expr": "sum( threadpool_active_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\",pool=\"Default_Executor\"} ) by ( pod )",
       "legendFormat": "{{pod}} -  active"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Rate of Logging",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }[2m]) ) by ( level )",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Rate of Warnings/Errors by Pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=~\"SEVERE|WARNING\"}[2m]) ) by ( pod ) ",
       "legendFormat": " {{pod}} "
      }
     ]
    },
    {
     "title": "Rate of Trace Messages by Pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=\"TRACE\"}[2m]) ) by ( pod ) ",
       "legendFormat": " {{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls - Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Calls (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))",
       "legendFormat": "Total Calls"
      }
     ]
    },
    {
     "title": "Call Status (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\" }[2m]))  by (http_status)",
       "legendFormat": "{{http_status}}"
      }
     ]
    },
    {
     "title": "Total Calls by Resource (per second)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))  by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls  - Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Average Response Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m]))  by (pod)  / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource,transaction)   / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource,transaction) > 0",
       "legendFormat": "{{resource}} {{transaction}}"
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m]))  by (resource,transaction) / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource,transaction) > 0",
       "legendFormat": "{{resource}} {{transaction}}"
      }
     ]
    },
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_rest_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\" }[2m])) by (resource,transaction,le)) > 0",
       "legendFormat": "{{resource}} {{transaction}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_rest_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\" }[2m])) by (resource,transaction,le)) > 0",
       "legendFormat": "{{resource}} {{transaction}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls - Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (per Second) - Cache Hits",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"hit\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Requests (per second) - Cache Misses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"miss\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Concurrency Limiters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "QueryApp Request - Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max(hcl_concurrency_limiter_capacity{name=\"RestHighLevelClientHelper.request\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(hcl_concurrency_limiter_threads_using{ name=\"RestHighLevelClientHelper.request\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "QueryApp Request - Waiting",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "max(hcl_concurrency_limiter_max_waiters{name=\"RestHighLevelClientHelper.request\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) < 1000",
       "legendFormat": "max_waiters"
      },
      {
       "expr": "sum(hcl_concurrency_limiter_threads_waiting{ name=\"RestHighLevelClientHelper.request\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Query - Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "max(hcl_concurrency_limiter_capacity{name=\"RestHighLevelClientHelper.call\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(hcl_concurrency_limiter_threads_using{ name=\"RestHighLevelClientHelper.call\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Elasticsearch Query - Waiting",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "max(hcl_concurrency_limiter_max_waiters{name=\"RestHighLevelClientHelper.call\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) < 1000",
       "legendFormat": "max_waiters"
      },
      {
       "expr": "sum(hcl_concurrency_limiter_threads_waiting{ name=\"RestHighLevelClientHelper.call\", namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Requests by Service",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( service_active_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" } ) by ( exported_service )",
       "legendFormat": "{{exported_service}}"
      }
     ]
    },
    {
     "title": "Total Calls (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_backend_seconds_count{ namespace=~\"$namespace\", pod=~\"$pod\"}[2m])) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_backend_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m]))  by (host) / sum(rate(request_backend_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) by (host) ",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_backend_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }[2m])) by (host,le))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_backend_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }[2m])) by (host,le))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}