{
 "title": "HCL Cache - Local Cache Details",
 "tags": [
  "hcl-cache",
  "hcl"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(hclcache_cache_size_max, namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(hclcache_cache_size_max{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(hclcache_cache_size_max{namespace=~\"$namespace\",job=~\"$job\"}, pod)"
    }
   },
   {
    "name": "cache",
    "label": "cache",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ namespace=~\"$namespace\", job=~\"$job\",pod=\"$pod\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br/>\n<h1>Local Cache Details</h1>"
   }
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "cache" },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 177 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 213 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 242 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 249 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 263 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 264 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 264 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 278 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 278 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 285 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 285 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 292 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 293 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 293 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 300 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 307 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 314 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 314 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 321 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 322 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 322 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 329 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 329 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 336 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 336 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 343 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 350 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 351 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 351 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 358 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 358 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 365 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 365 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 372 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 372 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 379 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 380 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 380 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 387 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 387 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 394 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 394 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 408 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 409 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 409 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 416 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 416 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 423 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 423 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 430 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 430 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 437 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 438 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 438 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 445 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 445 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 452 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 452 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 459 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 459 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 466 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 467 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 467 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 474 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 474 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 481 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 481 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 488 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 488 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  },
  { "title": "$cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 495 } },
  {
   "title": "Local Cache Size in Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 496 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 496 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Size in Mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 503 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "max"
    },
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "current"
    },
    {
     "expr": "hclcache_cache_size_mb_current_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }",
     "legendFormat": "scaled_max"
    }
   ]
  },
  {
   "title": "% Used in Mb",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 503 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "hclcache_cache_size_mb_current{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ namespace=~\"$namespace\", job=~ \"$job\", pod=~\"$pod\", scope=\"local\", name=\"$cache\" }"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit / Miss per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 510 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (result) (rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Local Cache Get Hit Ratios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 510 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Local Cache Operations per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 517 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removes_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "removes"
    },
    {
     "expr": "rate(hclcache_cache_clears_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "clear"
    },
    {
     "expr": "sum(rate(hclcache_cache_gets_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "get"
    },
    {
     "expr": "rate(hclcache_cache_invalidates_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "invalidate"
    },
    {
     "expr": "sum(rate(hclcache_cache_puts_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Local Cache Internal Removals  per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 517 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hclcache_cache_removals_expiry_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "expiry"
    },
    {
     "expr": "rate(hclcache_cache_removals_explicit_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "explicit"
    },
    {
     "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
     "legendFormat": "inactivity"
    },
    {
     "expr": "rate(hclcache_cache_removals_lru_total{ namespace=~\"$namespace\", job=~ \"$job\", pod=\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
     "legendFormat": "lru"
    }
   ]
  }
 ]
}