{
 "title": "NiFi Performance",
 "tags": [ "hcl" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nifipod",
    "query": {
     "query": "label_values(kube_pod_container_resource_requests_cpu_cores{container=\"nifi-app\"},pod)"
    }
   },
   { "name": "es_datasource", "label": "connector", "query": "elasticsearch" },
   { "name": "prometheus_datasource", "label": "prometheus_datasource", "query": "prometheus" },
   {
    "name": "connector",
    "label": "connector",
    "query": "{\"find\": \"terms\",  \"field\": \"connector\"}"
   },
   {
    "name": "runId",
    "label": "runId",
    "query": "{\"find\": \"terms\", \"field\": \"run\", \"query\": \"connector: $connector\"}"
   }
  ]
 },
 "panels": [
  { "title": "Ingest Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created Document Counters",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Write Success",
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND run: $runId  AND group: Create* AND name: \"Write Success\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "connector: $connector AND run: $runId AND group: Create* AND name: \"Write Failure\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": "Updated Document Counters ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Write Success",
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND run: $runId  AND NOT group: Create* AND name: \"Write Success\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "connector: $connector AND run: $runId AND NOT group: Create* AND name: \"Write Failure\"",
     "timeField": "date"
    }
   ]
  },
  {
   "title": " Elapsed Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Created Document Counter",
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Cumulative Elapsed Time\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Absolute Start Time\"",
     "timeField": "date"
    },
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "stage",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "group",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "value.numeric",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "connector: $connector AND  run: $runId AND name: \"Absolute End Time\"",
     "timeField": "date"
    }
   ]
  },
  { "title": "Nifi General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Queued Items",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( nifi_amount_items_queued{ component_type = 'ProcessGroup' } ) by ( component_type, component_name )",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Wait Link",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( nifi_amount_items_queued{ component_type = 'ProcessGroup', component_name =~ '.*WaitLink.*' } ) by ( component_type, component_name )",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Container - $nifipod  System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "nifipod",
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Used (%)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(nifi_jvm_heap_usage{pod=\"$nifipod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Heap Used (bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nifi_jvm_heap_used{pod=\"$nifipod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=\"$nifipod\"}",
       "legendFormat": "nifi-app"
      },
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{pod=\"$nifipod\"}\n",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{pod=\"$nifipod\"}\n",
       "legendFormat": "limits"
      }
     ]
    },
    {
     "title": "CPU Throttling ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{pod=\"$nifipod\", container=\"nifi-app\"}[5m])) /sum(increase(container_cpu_cfs_periods_total{pod=\"$nifipod\", container=\"nifi-app\"}[5m])) "
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{ pod=\"$nifipod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "working set"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=\"$nifipod\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=\"$nifipod\"})",
       "legendFormat": "limits"
      },
      {
       "expr": "sum(container_memory_cache{ pod=\"$nifipod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "cache"
      },
      {
       "expr": "sum(container_memory_swap{ pod=\"$nifipod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "swap"
      }
     ]
    },
    {
     "title": "Disk I/O - reads",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod=\"$nifipod\", container =\"nifi-app\"}[5m])) by (device)",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk I/O - writes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod=\"$nifipod\", container =\"nifi-app\"}[5m])) by (device)",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  }
 ]
}