{
 "title": "CRS Performance",
 "tags": [ "hcl" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(request_store_seconds_sum, kubernetes_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(request_store_seconds_sum{kubernetes_namespace=~\"$namespace\", component=~\".*crs-app\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "http_status",
    "label": "http_status",
    "query": {
     "query": "label_values(request_store_seconds_sum{kubernetes_namespace=~\"$namespace\", component=~\".*crs-app\"}, http_status)"
    }
   },
   {
    "name": "http_method",
    "label": "http_method",
    "query": {
     "query": "label_values(request_store_seconds_sum{kubernetes_namespace=~\"$namespace\", component=~\".*crs-app\"}, http_method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Calls by Status (per second)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_store_seconds_count{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m])) by ( http_status )",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_store_seconds_sum{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m]))  / sum(rate(request_store_seconds_count{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m]))",
     "legendFormat": "Avg Response Time"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Calls (per second)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 20, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_count{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Calls  (increase)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 20, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(request_store_seconds_count{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m])) by (kubernetes_pod_name)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_store_seconds_bucket{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" }[2m])) by (http_method,le))",
       "legendFormat": "{{http_method}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_store_seconds_bucket{ kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\", http_status=~\"$http_status\",http_method=~\"$http_method\" }[2m])) by (http_method,le))",
       "legendFormat": "{{http_method}}"
      }
     ]
    }
   ]
  }
 ]
}