{
 "title": "Java - Summary Metrics by Pod",
 "tags": [
  "hcl",
  "java"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, kubernetes_namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\"}, component)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\",component=~\"$job\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pod: $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_count{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "system_load_average_1m{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "pod: $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_count{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "system_load_average_1m{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "pod: $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_count{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "system_load_average_1m{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "pod: $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_count{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "system_load_average_1m{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "pod: $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_count{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "system_load_average_1m{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "pod: $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "system_cpu_count{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "cpu"
      },
      {
       "expr": "system_load_average_1m{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_states_threads{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "JVM Total Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"noheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"nonheap\"})  ",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Total JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", area=\"heap\"})  ",
       "legendFormat": "max"
      }
     ]
    }
   ]
  }
 ]
}