cluster:
  nodes: 3
  replicas: 0
persistence:
  enabled: true
image:
  registry: docker.io
  repository: bitnami/redis-cluster
  tag: 6.2.3-debian-10-r0
# disable if Prometheus-Operator is not used  
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
usePassword: false
redis:
  resources:
    limits:
      cpu: 2000m
      memory: 12Gi
    requests:
      cpu: 2000m
      memory: 12Gi
  useAOFPersistence: "no"
  configmap: |-
    save ""
    maxmemory 10000mb
    maxmemory-policy volatile-lru
    cluster-require-full-coverage no
    cluster-replica-validity-factor 0
#sysctlImage:
#  enabled: true
#  mountHostSys: true
#  pullPolicy: IfNotPresent  
#  command:
#    - /bin/sh
#    - -c
#    - |-
#      install_packages procps
#      sysctl -w net.core.somaxconn=10000
#      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
