{
 "title": "CRS Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(request_store_seconds_sum, namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*crs-app.*\"} , deployment) "
    }
   },
   {
    "name": "resource",
    "label": "crs-resource",
    "query": {
     "query": "label_values(request_store_seconds_count{namespace=~\"$namespace\",pod=~\"$job.*\"}, resource)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\",workload=\"$job\" }, pod)"
    }
   },
   {
    "name": "http_status",
    "label": "http_status",
    "query": {
     "query": "label_values(request_store_seconds_sum{namespace=~\"$namespace\", job=~\".*crs-app\"}, http_status)"
    }
   },
   {
    "name": "http_method",
    "label": "http_method",
    "query": {
     "query": "label_values(request_store_seconds_sum{namespace=~\"$namespace\", job=~\".*crs-app\"}, http_method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Image Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{ namespace=\"$namespace\", pod=~\"$pod\", container=\"crs-app\" }\r\n* on (pod)\r\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" } "
    }
   ]
  },
  {
   "title": "Request Status (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_store_seconds_count{ namespace=\"$namespace\", pod=~\"$pod\", service=\"$job\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m])) by ( http_status )",
     "legendFormat": "{{http_status}}"
    },
    {}
   ]
  },
  {
   "title": "Average Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_store_seconds_sum{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m]))  / sum(rate(request_store_seconds_count{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m]))",
     "legendFormat": "Avg Response Time"
    }
   ]
  },
  {
   "title": "crs-app pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{ namespace=\"$namespace\", deployment=\"$job\"   }  ",
     "legendFormat": "available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{ namespace=\"$namespace\", deployment=\"$job\" }",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Resources and Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used JVM Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(sum(jvm_memory_committed_bytes{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "commit"
      },
      {
       "expr": "max(sum(jvm_memory_max_bytes{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "If the CPU Usage is not shown, please check the query in the panel \"CPU Usage\" in the dashboard \"General/Kubernetes/Compute Resources/Pod\" to see whether \"sum_rate\" is used instead of \"sum_irate\".  If it is the case, please update sum_irate in Query A in this panel to sum_rate.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$pod\" }\n  * on(pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" }\n) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests {namespace=\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "quota-requests"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits {namespace=\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "quota-limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", container=\"crs-app\", pod=~\"$job.*\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", container=\"crs-app\", pod=~\"$job.*\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Default Executor Thread Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(threadpool_maximum_pool_size{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", pool=\"Default_Executor\" })",
       "legendFormat": "max"
      },
      {
       "expr": "sum( threadpool_active_pool_size{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\",pool=\"Default_Executor\"} ) by ( pod )",
       "legendFormat": "{{pod}} -  active"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Rate of Logging",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }[2m]) ) by ( level )",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Rate of Warnings/Errors by Pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=~\"SEVERE|WARNING\"}[2m]) ) by ( pod ) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Trace Messages by Pod",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=\"TRACE\"}[2m]) ) by ( pod ) ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Calls - Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Calls (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_count{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', resource=~\"$resource\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m]))"
      }
     ]
    },
    {
     "title": "Status  (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_count{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', resource=~\"$resource\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m])) by (http_status)",
       "legendFormat": "{{http_status}}"
      }
     ]
    },
    {
     "title": "Total Calls By Resource (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_count{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', resource=~\"$resource\", http_status=~\"$http_status\",http_method=~\"$http_method\" } [2m])) by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Calls - Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Average Response Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_sum{ namespace=~\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\"} [2m]))  by (pod)  / sum(rate(request_store_seconds_count{ namespace=~\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\"} [2m])) by (pod)"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_sum{ namespace=\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\"} [2m])) by (resource)   / sum(rate(request_store_seconds_count{ namespace=\"$namespace\",  pod=~\"$job.*\", resource=~\"$resource\"} [2m])) by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_sum{ namespace=\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\"} [2m]))  by (resource) / sum(rate(request_store_seconds_count{ namespace=~\"$namespace\",  pod=~\"$job.*\", resource=~\"$resource\"} [2m])) by (resource) ",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_store_seconds_bucket{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', resource=~\"$resource\", http_status=~\"$http_status\",http_method=~\"$http_method\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_store_seconds_bucket{ namespace=\"$namespace\", pod=~\"$pod\", service='$job', resource=~\"$resource\", http_status=~\"$http_status\",http_method=~\"$http_method\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Calls - Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (per second) -- Cache Hits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\", cache =\"hit\" }[2m]))  by ( resource) > 0",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Requests (per second) - Cache Misses",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\", cache =\"miss\" }[2m]))  by ( resource) > 0",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratios by Request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\",  pod=~\"$job.*\", resource=~\"$resource\", cache =\"hit\" }[2m]))  by ( resource) / sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$job.*\", resource=~\"$resource\"}[2m]))  by ( resource)  ",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  }
 ]
}