{
 "title": "Nextjs Store Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "hcl" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{container=\"nextjs-app\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*nextjs-app.*\"} , deployment)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\",workload=\"$job\" }, pod)"
    }
   },
   {
    "name": "workerId",
    "label": "workerId",
    "query": {
     "query": "label_values(nodejs_version_info{ namespace=\"$namespace\" , job=\"$job\", pod=\"$pod\"  }, worker_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Image",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{ namespace=\"$namespace\", pod=~\"$pod\", container=\"nextjs-app\" }\r\n* on(pod)\r\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" } \r\n"
    }
   ]
  },
  {
   "title": "Request Status (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nextjs_http_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}[2m])) by (http_status)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(nextjs_http_request_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"} [2m])) / sum(rate(nextjs_http_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"} [2m]))  > 0",
     "legendFormat": "avg_resp"
    }
   ]
  },
  {
   "title": "nextjs-app pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{ namespace=\"$namespace\", deployment=~\"$job\"   }  ",
     "legendFormat": "available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{ namespace=\"$namespace\", deployment=~\"$job\" }",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Resources and Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "If the CPU Usage is not shown, please check the query in the panel \"CPU Usage\" in the dashboard \"General/Kubernetes/Compute Resources/Pod\" to see whether \"sum_rate\" is used instead of \"sum_irate\".  If it is the case, please update sum_irate in Query A in this panel to sum_rate.",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$pod\", container=\"nextjs-app\" }\n  * on(pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" }\n) by (pod)\n",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota - requests"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota - limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"nextjs-app\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"nextjs-app\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}",
       "legendFormat": "{{pod}}/{{worker_id}}"
      }
     ]
    },
    {
     "title": "Process Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}",
       "legendFormat": "{{pod}}/{{worker_id}}"
      }
     ]
    },
    {
     "title": "Active Handles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}",
       "legendFormat": "{{pod}}/{{worker_id}}"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_requests_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}",
       "legendFormat": "{{pod}}/{{worker_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Store Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(nextjs_http_request_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"} [2m])) by (pod) / sum(rate(nextjs_http_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"} [2m])) by (pod)  > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Response Times - 95 Percentile Analysis",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(nextjs_http_request_duration_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}[2m])) by (pod,le)) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Request Status (per second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(nextjs_http_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}[2m])) by (pod, http_status)",
       "legendFormat": "{{pod}} http_status {{http_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Calls (per second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(nextjs_backend_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*query-app.*\"}[2m]))",
       "legendFormat": "query-app"
      },
      {
       "expr": "sum(rate(nextjs_backend_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*ts-app.*\"}[2m])) ",
       "legendFormat": "ts-app"
      }
     ]
    },
    {
     "title": "Backend Calls - Average Response Times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(nextjs_backend_request_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*query-app.*\"} [2m]))  / sum(rate(nextjs_backend_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*query-app.*\"} [2m]))",
       "legendFormat": "query-app"
      },
      {
       "expr": "sum(rate(nextjs_backend_request_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*ts-app.*\"} [2m])) / sum(rate(nextjs_backend_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*ts-app.*\"} [2m])) ",
       "legendFormat": "ts-app"
      }
     ]
    },
    {
     "title": "Backend Calls - 95 Percentile Analysis",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(nextjs_backend_request_duration_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*query-app.*\"}[2m])) by (le)) > 0",
       "legendFormat": "query-app"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(nextjs_backend_request_duration_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", hostname=~\".*ts-app.*\"}[2m])) by (le)) > 0",
       "legendFormat": "ts-app "
      }
     ]
    }
   ]
  },
  {
   "title": "$pod details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(nextjs_http_request_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"} [2m])) by (worker_id) / sum(rate(nextjs_http_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"} [2m])) by (worker_id)  > 0",
       "legendFormat": "{{worker_id}}"
      }
     ]
    },
    {
     "title": "Request Status (per second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 13 },
     "targets": [
      {
       "expr": "sum(rate(nextjs_http_request_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}[2m])) by (worker_id,http_status)",
       "legendFormat": "http_status {{http_status}}/{{worker_id}}"
      }
     ]
    },
    {
     "title": "GC Duration by Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(nodejs_gc_duration_seconds_sum{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}) by (kind, worker_id) / sum(nodejs_gc_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}) by (kind,worker_id)",
       "legendFormat": "{{kind}}/{{worker_id}}"
      }
     ]
    },
    {
     "title": "Process Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}",
       "legendFormat": "{{worker_id}}"
      }
     ]
    },
    {
     "title": "Total GC by Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 22 },
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\"}[$__range])) by (worker_id,kind)",
       "legendFormat": "{{kind}}/{{worker_id}}"
      }
     ]
    },
    {
     "title": "Major GC Frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nodejs_gc_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", kind=\"major\"}[2m])) by (worker_id)",
       "legendFormat": "{{worker_id}}"
      }
     ]
    },
    {
     "title": "Minor GC Frequency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nodejs_gc_duration_seconds_count{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", worker_id=~\"$workerId\", kind=\"minor\"}[2m])) by (worker_id)",
       "legendFormat": "{{worker_id}}"
      }
     ]
    }
   ]
  }
 ]
}