{
 "title": "Orchestration App",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{container=\"orchestration-app\"}, namespace)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*orchestration-app.*\"} , deployment) "
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*$env.*orchestration-app.*\"} , deployment) "
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\",workload=\"$job\" }, pod)"
    }
   },
   { "name": "container", "query": "orchestration-app" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Image",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{ namespace=\"$namespace\", pod=~\"$pod\", container=\"orchestration-app\" }\r\n* on(pod)\r\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" } \r\n"
    }
   ]
  },
  {
   "title": "Requests Status (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[2m]))  by (status) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) by (pod) / sum(rate(http_server_requests_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "orchestration-app pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{ namespace=\"$namespace\", deployment=~\"$job\"}) by (namespace,job)",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{ namespace=\"$namespace\", deployment=~\"$job\" }) by (namespace,job)",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Resources and Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Java",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "jvm_info{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "If the CPU Usage is not shown, please check the query in the panel \"CPU Usage\" in the dashboard \"General/Kubernetes/Compute Resources/Pod\" to see whether \"sum_rate\" is used instead of \"sum_irate\".  If it is the case, please update sum_irate in Query A in this panel to sum_rate.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\" }\n  * on(pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" }\n) by (pod)\n",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota-requests"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota-limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"$container\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Used JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(sum(jvm_memory_committed_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "committed"
      }
     ]
    },
    {
     "title": "Tomcat Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(tomcat_threads_busy_threads{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}} - busy"
      },
      {
       "expr": "max(tomcat_threads_config_max_threads{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
       "legendFormat": "max"
      },
      {
       "expr": "tomcat_threads_current_threads{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}",
       "legendFormat": "{{pod}} - current"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging (logback)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Rate of Logging",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }[2m]) ) by (level)",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Rate of Warnings/Errors by Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=~\"error|warn\"}[2m]) ) by (pod)",
       "legendFormat": " {{pod}} "
      }
     ]
    },
    {
     "title": "Rate of Info and Trace Messages by Pod",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=~\"info|trace|debug\"}[2m])) by (pod)",
       "legendFormat": " {{pod}} "
      }
     ]
    },
    {
     "title": "Thread Monitor Dumps by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(thread_monitor_threaddumps_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Camel Event Notifiers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Camel Event Notifiers (per second)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(camel_exchange_event_notifier_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[2m])) by (routeId,eventType,endpointName) > 0",
       "legendFormat": "{{routeId}}:{{eventType}}:{{endpointName}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum(rate(camel_exchange_event_notifier_seconds_sum{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) by (routeId,eventType,endpointName) / sum(rate(camel_exchange_event_notifier_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[2m])) by (routeId,eventType,endpointName)) > 0",
       "legendFormat": "{{routeId}}:{{eventType}}:{{endpointName}}"
      }
     ]
    },
    {
     "title": "Maximum Response Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(camel_exchange_event_notifier_seconds_max{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}) by (routeId,eventType,endpointName) > 0",
       "legendFormat": "{{routeId}}:{{eventType}}:{{endpointName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Camel Route Exchanges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Camel Routes (per second)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(camel_route_policy_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\",eventType=\"route\"}[2m])) by (routeId) > 0",
       "legendFormat": "{{routeId}}"
      },
      {
       "expr": "sum(rate(camel_route_policy_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\",eventType=\"context\"}[2m]))",
       "legendFormat": "context"
      }
     ]
    },
    {
     "title": "Camel Routes - Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 10, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum(rate(camel_route_policy_seconds_sum{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"route\"} [2m])) by (routeId) / sum(rate(camel_route_policy_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"route\"} [2m])) by (routeId)) > 0",
       "legendFormat": "{{routeId}}"
      }
     ]
    },
    {
     "title": "In Flight",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(camel_exchanges_inflight{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) by (routeId)",
       "legendFormat": "{{routeId}}"
      }
     ]
    },
    {
     "title": "Succeeded Exchanges (per second)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 5, "x": 5, "y": 41 },
     "targets": [
      {
       "expr": "sum(rate(camel_exchanges_succeeded_total{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m]))",
       "legendFormat": "succeeded"
      },
      {
       "expr": "sum(rate(camel_exchanges_failed_total{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Failed (Handled) Exchanges (per second)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 10, "y": 41 },
     "targets": [
      {
       "expr": "rate(camel_exchanges_failures_handled_total{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"route\"} [2m]) ",
       "legendFormat": "{{routeId}}"
      },
      {
       "expr": "rate(camel_exchanges_failures_handled_total{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"context\"} [2m])",
       "legendFormat": "context"
      }
     ]
    },
    {
     "title": "Failed Exchanges (per second)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 5, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "rate(camel_exchanges_failed_total{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"route\"} [2m])",
       "legendFormat": "{{routeId}}"
      },
      {
       "expr": "rate(camel_exchanges_failed_total{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"context\"} [2m])",
       "legendFormat": "context"
      }
     ]
    }
   ]
  },
  {
   "title": "Camel Route Exchanges - Outbound HTTP Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Outbound Calls - Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum(rate(camel_exchange_event_notifier_seconds_sum{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"ExchangeSentEvent\", endpointName =~ \"https://.*\"} [2m])) by (endpointName) / sum(rate(camel_exchange_event_notifier_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\",eventType=\"ExchangeSentEvent\", endpointName =~ \"https://.*\"}[2m])) by (endpointName)) > 0",
       "legendFormat": "{{endpointName}}"
      },
      {
       "expr": "sum(rate(otel_traces_httpmetrics_duration_seconds_sum{namespace=\"$namespace\", deployment=\"$job\",pod=~\"$pod\"}[2m])) by (server_address) / sum(rate(otel_traces_httpmetrics_duration_seconds_count{namespace=\"$namespace\", deployment=\"$job\",pod=~\"$pod\"}[2m])) by (server_address)",
       "legendFormat": "{{server_address}} (OTel)"
      }
     ]
    },
    {
     "title": "HTTP Outbound Calls  (per second)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(camel_exchange_event_notifier_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\",eventType=\"ExchangeSentEvent\", endpointName =~ \"https://.*\"}[2m])) by (endpointName) > 0",
       "legendFormat": "{{endpointName}}"
      },
      {
       "expr": "sum(rate(otel_traces_httpmetrics_calls_total{namespace=\"$namespace\", deployment=\"$job\",pod=~\"$pod\"}[2m])) by (server_address) > 0",
       "legendFormat": "{{server_address}} (OTel)"
      }
     ]
    },
    {
     "title": "Local vs Outbound (HTTP) Average Times",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 7, "x": 14, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(otel_traces_httpmetrics_duration_seconds_sum{namespace=\"$namespace\", deployment=\"$job\",pod=~\"$pod\"}[2m])) / \r\nsum(rate(otel_traces_httpmetrics_duration_seconds_count{namespace=\"$namespace\", deployment=\"$job\",pod=~\"$pod\"}[2m]))\r\n",
       "legendFormat": "Outbound (OTel)"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) / sum(rate(http_server_requests_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m]))",
       "legendFormat": "Local"
      },
      {
       "expr": "(sum(rate(camel_exchange_event_notifier_seconds_sum{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\", eventType=\"ExchangeSentEvent\", endpointName =~ \"https://.*\"} [2m])) / sum(rate(camel_exchange_event_notifier_seconds_count{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\",eventType=\"ExchangeSentEvent\", endpointName =~ \"https://.*\"}[2m])) ) > 0",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Calls (per second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"}[2m]))  by (uri,status) > 0",
       "legendFormat": "{{uri}}: {{status}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum(rate(http_server_requests_seconds_sum{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) by (uri,status) / sum(rate(http_server_requests_seconds_count{ namespace=\"$namespace\", job=~\"$job\", pod=~\"$pod\"} [2m])) by (uri,status))> 0",
       "legendFormat": "{{uri}}:{{status}}"
      }
     ]
    },
    {
     "title": "HTTP Active Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(http_server_requests_active_seconds_active_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }-1) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authorizations (per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(spring_security_authorizations_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[2m])) by (spring_security_authentication_type)",
       "legendFormat": "{{authentication_request_type}}"
      }
     ]
    },
    {
     "title": "Authorizations Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(spring_security_authorizations_seconds_sum{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} [2m])) by (spring_security_authentication_type) / sum(rate(spring_security_authorizations_seconds_count{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} [2m])) by (spring_security_authentication_type)",
       "legendFormat": "{{authentication_request_type}}"
      }
     ]
    },
    {
     "title": "Authentications (per second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(spring_security_authentications_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[2m])) by (authentication_request_type)",
       "legendFormat": "{{authentication_request_type}}"
      }
     ]
    },
    {
     "title": "Authentications Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(spring_security_authentications_seconds_sum{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} [2m])) by (authentication_request_type) / sum(rate(spring_security_authentications_seconds_count{ namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\"} [2m])) by (authentication_request_type)",
       "legendFormat": "{{authentication_request_type}}"
      }
     ]
    }
   ]
  }
 ]
}