{
 "title": "Transaction Servers",
 "tags": [ "hcl" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{container=\"ts-app\"}, namespace)"
    }
   },
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*ts-app.*\"} , deployment) "
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"$namespace\",deployment=~\".*$env.*ts-app.*\"} , deployment) "
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\",workload=\"$job\" }, pod)"
    }
   },
   {
    "name": "resource",
    "label": "ts-resource",
    "query": {
     "query": "label_values(request_rest_seconds_count{namespace=~\"$namespace\",job=\"$job\",pod=~\"$pod\"}, resource)"
    }
   },
   {
    "name": "crsresource",
    "label": "crs-resource",
    "query": {
     "query": "label_values(request_store_seconds_count{namespace=~\"$namespace\",pod=~\"$env.*ts-app.*\"}, resource)"
    }
   },
   {
    "name": "http_status",
    "label": "http_status",
    "query": {
     "query": "label_values(request_rest_status_total{namespace=~\"$namespace\",job=\"$job\",pod=~\"$pod\",resource=~\"$resource\"}, http_status)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Image",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_info{ namespace=\"$namespace\", pod=~\"$pod\", container=\"ts-app\" }\r\n* on(pod)\r\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" } \r"
    }
   ]
  },
  {
   "title": "Requests Status (per second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\" }[2m]))  by (http_status) or sum(rate(request_store_status_total{ namespace=~\"$namespace\",  pod=~\"$env.*ts-app.*\", resource=~\"$resource\", http_status=~\"$http_status\" }[2m]))  by (http_status) )  by (http_status)",
     "legendFormat": "{{http_status}}"
    }
   ]
  },
  {
   "title": "Average Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum( sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (job) / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (job) or sum(rate(request_store_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$crsresource\"} [2m])) by (job) / sum(rate(request_store_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$crsresource\"} [2m])) by (job) ) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "ts-app pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{ namespace=\"$namespace\", deployment=~\"$job\"   }  ",
     "legendFormat": "available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{ namespace=\"$namespace\", deployment=~\"$job\" }",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Resources and Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Used JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max (sum(jvm_memory_committed_bytes{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "committed"
      },
      {
       "expr": "max(sum(jvm_memory_max_bytes{namespace=\"$namespace\", job=\"$job\", pod=~\"$pod\", area=\"heap\"}) by (pod))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "If the CPU Usage is not shown, please check the query in the panel \"CPU Usage\" in the dashboard \"General/Kubernetes/Compute Resources/Pod\" to see whether \"sum_rate\" is used instead of \"sum_irate\".  If it is the case, please update sum_irate in Query A in this panel to sum_rate.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$pod\", container=\"ts-app\" }\n  * on(pod)\n    group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{ namespace=\"$namespace\", workload_type=\"deployment\", workload=\"$job\" }\n) by (pod)\n",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota-requests"
      },
      {
       "expr": "max( cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits {namespace=\"commerce\", pod=~\"$pod\"})",
       "legendFormat": "quota-limits"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"ts-app\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=\"ts-app\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "WebContainer Thread pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(threadpool_maximum_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", pool=\"WebContainer\" })",
       "legendFormat": "max"
      },
      {
       "expr": "sum( threadpool_active_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\",pool=\"WebContainer\"} ) by ( pod )",
       "legendFormat": "{{pod}} -  active"
      }
     ]
    },
    {
     "title": "WCDataSource",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(datasource_maximum_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" })",
       "legendFormat": "max"
      },
      {
       "expr": "sum(datasource_current_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }) by ( pod )",
       "legendFormat": "{{pod}} - allocated"
      },
      {
       "expr": "sum( datasource_current_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" } - datasource_free_pool_size{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }) by ( pod )",
       "legendFormat": "{{pod}} -  in-use"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Rate of Logging",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\" }[2m]) ) by ( level )",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Rate of Warnings/Errors by Pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=~\"SEVERE|WARNING\"}[2m]) ) by ( pod ) ",
       "legendFormat": " {{pod}} "
      }
     ]
    },
    {
     "title": "Rate of Trace Messages by Pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate(java_logging_messages_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", level=\"TRACE\"}[2m]) ) by ( pod ) ",
       "legendFormat": " {{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Access Bean (Database) Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bean Method Executions (per second) - Cache Hits ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(access_bean_cache_seconds_count{ namespace=~\"$namespace\", pod=~\"$job.*\", cache =\"hit\" }[2m])) by (bean,finder)> 0\r",
       "legendFormat": "{{bean}}.{{finder}}"
      }
     ]
    },
    {
     "title": "Bean Method Executions (per second) - Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(access_bean_cache_seconds_count{ namespace=~\"$namespace\", pod=~\"$job.*\", cache =\"miss\" }[2m])) by (bean,finder)  > 0\r",
       "legendFormat": "{{bean}}.{{finder}}"
      }
     ]
    },
    {
     "title": "Bean Cache Hit Ratios by Method",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(access_bean_cache_seconds_count{ namespace=~\"$namespace\",  pod=~\"$job.*\", cache =\"hit\" }[2m]))  by ( bean,finder) / sum(rate(access_bean_cache_seconds_count{ namespace=~\"$namespace\", pod=~\"$job.*\"}[2m]))  by (bean,finder)  > 0\r",
       "legendFormat": "{{bean}}.{{finder}}"
      }
     ]
    },
    {
     "title": "Average Execution Time - Bean Cache Hits",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(access_bean_cache_seconds_sum{ namespace=\"$namespace\", pod=~\"$job.*\", cache =\"hit\" }[2m])) by (bean,finder) / sum(rate(access_bean_cache_seconds_count {namespace=\"$namespace\", pod=~\"$job.*\", cache=\"hit\"} [2m])) by (bean,finder) > 0\r",
       "legendFormat": "{{bean}}.{{finder}}"
      }
     ]
    },
    {
     "title": "Average Execution Time - Bean Cache Misses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(access_bean_cache_seconds_sum{ namespace=\"$namespace\", pod=~\"$job.*\", cache =\"miss\" }[2m])) by (bean,finder) / sum(rate(access_bean_cache_seconds_count {namespace=\"$namespace\", pod=~\"$job.*\", cache=\"miss\"} [2m])) by (bean,finder) > 0\r\n",
       "legendFormat": "{{bean}}.{{finder}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls  - Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Calls (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))",
       "legendFormat": "Total Calls/sec"
      }
     ]
    },
    {
     "title": "Call Status (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\" }[2m]))  by (http_status)",
       "legendFormat": "{{http_status}}"
      }
     ]
    },
    {
     "title": "Total Calls by Resource (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", http_status=~\"$http_status\"}[2m]))  by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls - Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Average Response Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m]))  by (pod)  / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource)   / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_seconds_sum{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m]))  by (resource) / sum(rate(request_rest_seconds_count{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"} [2m])) by (resource) ",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_rest_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_rest_seconds_bucket{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST Calls - Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (per second) - Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"hit\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Requests (per second) - Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"miss\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratios by Request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\", cache =\"hit\" }[2m]))  by ( resource) / sum(rate(request_rest_status_total{ namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\", resource=~\"$resource\"}[2m]))  by ( resource)  \r",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Store Calls  - Executions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Calls (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=\"$namespace\", pod=~\"$env.*ts-app.*\", http_status=~\"$http_status\", resource=~\"$crsresource\"}[2m]))",
       "legendFormat": "Total Calls/sec"
      }
     ]
    },
    {
     "title": "Call Status (per second)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\",  http_status=~\"$http_status\"}[2m]))  by (http_status)",
       "legendFormat": "{{http_status}} "
      }
     ]
    },
    {
     "title": " Total Calls by Resource (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\", http_status=~\"$http_status\"}[2m]))  by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Store Calls - Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Average Response Time",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_sum{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"} [2m]))  by (pod)  / sum(rate(request_store_seconds_count{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"} [2m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_sum{ namespace=\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"} [2m])) by (resource)   / sum(rate(request_store_seconds_count{ namespace=\"$namespace\",  pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"} [2m])) by (resource) > 0",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_seconds_sum{ namespace=\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"} [2m]))  by (resource) / sum(rate(request_store_seconds_count{ namespace=~\"$namespace\",  pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"} [2m])) by (resource) ",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "95 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(request_store_seconds_bucket{ namespace=~\"$namespace\",  pod=~\"$env.*ts-app.*\", resource=~\"$resource\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "99 Percentile Analysis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 166 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(request_store_seconds_bucket{ namespace=~\"$namespace\",  pod=~\"$env.*ts-app.*\", resource=~\"$resource\" }[2m])) by (resource,le))",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Local Store Calls - Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests (per second) - Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\", cache =\"hit\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Requests (per second) - Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\", cache =\"miss\" }[2m]))  by ( resource) > 0\r",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Cache Hit Ratios by Request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 183 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(request_store_status_total{ namespace=~\"$namespace\",  pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\", cache =\"hit\" }[2m]))  by ( resource) / sum(rate(request_store_status_total{ namespace=~\"$namespace\", pod=~\"$env.*ts-app.*\", resource=~\"$crsresource\"}[2m]))  by ( resource)  \r",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  }
 ]
}