{
 "title": "HCL Cache - Remote",
 "tags": [
  "hcl-cache",
  "hcl"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(hclcache_cache_size_max, kubernetes_namespace)"
    }
   },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ kubernetes_namespace=\"$namespace\"}, cachespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ kubernetes_namespace=~\"$namespace\", cachespace=\"$environment\"}, component)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "cache",
    "label": "cache",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"},name)"
    }
   },
   {
    "name": "redis",
    "query": {
     "query": "label_values(hclcache_cache_remote_node_mapping{ cachespace=\"$environment\" },redis_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients Currently in Outage Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hclcache_remoteclient_outage{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Remote Clients in Outage Mode",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hclcache_remoteclient_outage{kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$component\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name) > 0",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Caches Currently in Outage Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hclcache_cache_outage{kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Remote Caches in Outage Mode",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hclcache_cache_outage{kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remote Cache Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Cache Sizes",
     "type": "graph",
     "description": "Cache Manager pod must be enabled",
     "gridPos": { "h": 12, "w": 16, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max( (  hclcache_cache_size_current{  kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", scope=\"remote\", result!=\"error\", name=~\"$cache\" } > 0 ) * on (  kubernetes_pod_name, kubernetes_namespace, cachespace, name) group_left( redis_instance ) hclcache_cache_remote_node_mapping{ redis_instance =~ \"$redis\"  }) by ( name, redis_instance )  ",
       "legendFormat": "{{redis_instance}} - {{name}}"
      }
     ]
    },
    {
     "title": "Redis Memory",
     "type": "graph",
     "description": "This dashboard only works if Redis is installed\nlocally with metrics enabled",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "redis_memory_used_bytes", "legendFormat": "{{instance}} - {{pod}} used" },
      { "expr": "max(redis_memory_max_bytes)", "legendFormat": "max" }
     ]
    }
   ]
  },
  {
   "title": "Remote Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Operations per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_puts_duration_seconds_count{  kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "put"
      },
      {
       "expr": "sum(rate(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "get"
      },
      {
       "expr": "sum(rate(hclcache_cache_clears_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "clear"
      },
      {
       "expr": "sum(rate(hclcache_cache_invalidates_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result!=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "invalidate"
      }
     ]
    },
    {
     "title": "Remote Error Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(hclcache_cache_puts_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", componenet=~\"$job\",  kubernetes_pod_name=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "put"
      },
      {
       "expr": "sum(increase(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", componenet=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "get"
      },
      {
       "expr": "sum(increase(hclcache_cache_clears_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", componenet=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "clear"
      },
      {
       "expr": "sum(increase(hclcache_cache_invalidates_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", componenet=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "invalidate"
      }
     ]
    },
    {
     "title": "Get Ops per Cache per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "\r\nsum(rate(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) by (name) > 0\r\r",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Put Ops per Cache per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_puts_duration_seconds_count{ kubernetes_namespace=\"$namespace\",cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]) ) by (name) ",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Clear Ops per Cache per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_clears_duration_seconds_count{ kubernetes_namespace=\"$namespace\",cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]) ) by (name) ",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Invalidate Ops per Cache per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_invalidates_duration_seconds_count{ kubernetes_namespace=\"$namespace\",cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]) ) by (name) ",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Average Durations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_gets_duration_seconds_sum{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
       "legendFormat": "get"
      },
      {
       "expr": "sum(rate(hclcache_cache_puts_duration_seconds_sum{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_puts_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
       "legendFormat": "put"
      },
      {
       "expr": "sum(rate(hclcache_cache_removes_duration_seconds_sum{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_puts_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
       "legendFormat": "remove"
      },
      {
       "expr": "sum(rate(hclcache_cache_invalidates_duration_seconds_sum{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m])) / sum(rate(hclcache_cache_puts_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[2m]))",
       "legendFormat": "invalidate"
      }
     ]
    },
    {
     "title": "Remote Operations - 95% Percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_gets_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
       "legendFormat": "get"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_puts_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\"}[5m])) by (le))",
       "legendFormat": "put "
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_clears_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\"}[5m])) by (le))",
       "legendFormat": "clear"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_invalidates_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\",  component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
       "legendFormat": "invalidate"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(hclcache_cache_removes_duration_seconds_bucket{kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
       "legendFormat": "remove"
      }
     ]
    },
    {
     "title": "Remote Operations - 99% Percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_gets_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\",  component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\"  }[5m])) by (le))",
       "legendFormat": "get"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_puts_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\"}[5m])) by (le))",
       "legendFormat": "put "
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_clears_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
       "legendFormat": "clear"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_invalidates_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
       "legendFormat": "invalidate"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hclcache_cache_removes_duration_seconds_bucket{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"remote\", name=~\"$cache\" }[5m])) by (le))",
       "legendFormat": "remove"
      }
     ]
    }
   ]
  },
  {
   "title": "Hit Ratios",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Gets per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (result) (rate(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\", scope=\"remote\", result !=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Remote Hit Ratio",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 13, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\", scope=\"remote\", result =\"hit\", name=~\"$cache\"}[2m])) / sum(rate(hclcache_cache_gets_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\",  scope=\"remote\", result !=\"error\", name=~\"$cache\"}[2m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Invalidation Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dependency Invalidation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_invalidation_messages_total{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\", type=\"dependency\", name=~\"$cache\"} [2m] ) ) by (name) > 0",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cache Clear Invalidation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 13, "x": 11, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_invalidation_messages_total{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\", type=\"clear\", name=~\"$cache\"}[2m])) by (name) > 0",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Expired Keys Pending Maintenance",
     "type": "graph",
     "description": "This chart shows the number of keys  that have expired and are pending to be removed by the maintenance processes. Large numbers could indicate maintenance is failing or behind\nCache Manager pod must be enabled\n",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( hclcache_cache_size_maintenance{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\",  scope=\"remote\", name=~\"$cache\" } ) by ( name )  > 0",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rate of Expired Keys Removed by Cache",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate( hclcache_cache_maintenance_online_keys_total{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\", scope=\"remote\", result!=\"error\", name=~\"$cache\", scope=\"remote\", type=\"expired\" }[5m]) > 0 ) by  (name) ",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Low-Memory Maintenance - Paused PUT Operations by Cache",
     "type": "graph",
     "description": "When the HCL Cache detects that the memory in Redis is almost full, it can temporarily stop PUT operations while Low-Memory maintenance is running ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( hclcache_cache_remote_put_paused{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\", name=~\"$cache\" } ) by (name)  > 0",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rate of Keys Maintained by Type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( rate( hclcache_cache_maintenance_online_keys_total{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=~\"$environment\",  scope=\"remote\", result!=\"error\", name=~\"$cache\", scope=\"remote\" }[5m]  ) ) by  ( type )",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum( rate( hclcache_cache_maintenance_online_keys_total{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", result=\"error\", name=~\"$cache\", scope=\"remote\" }[5m]  ) ) by  ( type )",
       "legendFormat": "{{type}}-error"
      }
     ]
    },
    {
     "title": "Maintenance Average Durations",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_maintenance_online_duration_seconds_sum{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=\"$environment\",  scope=\"remote\", name=~\"$cache\", type=\"expired\" }[2m]) ) \r\n / sum(rate(hclcache_cache_maintenance_online_duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", cachespace=\"$environment\",  scope=\"remote\", name=~\"$cache\", type=\"expired\"}[2m]))\r",
       "legendFormat": "expired"
      },
      {
       "expr": "sum(rate(hclcache_cache_maintenance_online_duration_seconds_sum{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\", type=\"emergency\" }[2m]) ) \r\n / sum(rate(hclcache_cache_maintenance_online__duration_seconds_count{ kubernetes_namespace=\"$namespace\", cachespace=\"$environment\", job=~\"$job\", pod=~\"$pod\", scope=\"remote\", name=~\"$cache\", type=\"emergency\"}[2m]))\r",
       "legendFormat": "emergency"
      }
     ]
    }
   ]
  }
 ]
}