{
 "title": "HCL Cache - Local Cache Details",
 "tags": [
  "hcl-cache",
  "hcl"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(hclcache_cache_size_max, kubernetes_namespace)"
    }
   },
   {
    "name": "job",
    "label": "deployment",
    "query": {
     "query": "label_values(hclcache_cache_size_max{kubernetes_namespace=~\"$namespace\"}, component)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(hclcache_cache_size_max{kubernetes_namespace=~\"$namespace\",component=~\"$job\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "cache",
    "label": "cache",
    "query": {
     "query": "label_values(hclcache_cache_size_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\",kubernetes_pod_name=\"$pod\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br/>\n<h1>Local Cache Details</h1>"
   }
  },
  {
   "title": "$cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "cache",
   "collapsed": true,
   "panels": [
    {
     "title": "Local Cache Size in Entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hclcache_cache_size_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }",
       "legendFormat": "max"
      },
      {
       "expr": "hclcache_cache_size_current{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }",
       "legendFormat": "current"
      },
      {
       "expr": "hclcache_cache_size_current_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }",
       "legendFormat": "scaled_max"
      }
     ]
    },
    {
     "title": "% Used in Entries",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hclcache_cache_size_current{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }"
      }
     ]
    },
    {
     "title": "Local Cache Size in Mb",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hclcache_cache_size_mb_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }",
       "legendFormat": "max"
      },
      {
       "expr": "hclcache_cache_size_mb_current{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }",
       "legendFormat": "current"
      },
      {
       "expr": "hclcache_cache_size_mb_current_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }",
       "legendFormat": "scaled_max"
      }
     ]
    },
    {
     "title": "% Used in Mb",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 11, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "hclcache_cache_size_mb_current{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" } / hclcache_cache_size_mb_max{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }"
      }
     ]
    },
    {
     "title": "Local Cache Get Hit / Miss per sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (result) (rate(hclcache_cache_gets_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\"}[5m]))",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Local Cache Get Hit Ratios",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 11, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_gets_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\", result=\"hit\"}[2m])) / (sum(rate(hclcache_cache_gets_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\"}[2m])))",
       "legendFormat": "hit ratio"
      }
     ]
    },
    {
     "title": "Local Cache Operations per sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_removes_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
       "legendFormat": "removes"
      },
      {
       "expr": "rate(hclcache_cache_clears_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
       "legendFormat": "clear"
      },
      {
       "expr": "sum(rate(hclcache_cache_gets_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
       "legendFormat": "get"
      },
      {
       "expr": "rate(hclcache_cache_invalidates_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
       "legendFormat": "invalidate"
      },
      {
       "expr": "sum(rate(hclcache_cache_puts_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m])) ",
       "legendFormat": "put"
      }
     ]
    },
    {
     "title": "Local Cache Internal Removals  per sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hclcache_cache_removals_expiry_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
       "legendFormat": "expiry"
      },
      {
       "expr": "rate(hclcache_cache_removals_explicit_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
       "legendFormat": "explicit"
      },
      {
       "expr": "sum(rate(hclcache_cache_removals_inactivity_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m]))",
       "legendFormat": "inactivity"
      },
      {
       "expr": "rate(hclcache_cache_removals_lru_total{ kubernetes_namespace=~\"$namespace\", component=~\"$job\", kubernetes_pod_name=~\"$pod\", scope=\"local\", name=\"$cache\" }[5m])",
       "legendFormat": "lru"
      }
     ]
    }
   ]
  }
 ]
}